#!/usr/bin/env node
// Offline only: emits entries for operator review; never edits config or contacts Azure.
import { isIP } from "node:net";
import path from "node:path";
import { parseArgs } from "node:util";
import { pathToFileURL } from "node:url";

export function gatewayEntries({ nodeId, ip, tls, name, region = "Private VNet", dataPort = "8443", workspacePort = "3001" }) {
  if (!/^n-[a-f0-9]{24}$/.test(nodeId ?? "")) {
    throw new Error("Use the new node ID generated by Codey enrollment, not a display name or legacy ID.");
  }
  const [a, b] = String(ip).split(".").map(Number);
  if (isIP(String(ip)) !== 4 || !(a === 10 || (a === 172 && b >= 16 && b <= 31) || (a === 192 && b === 168))) {
    throw new Error("The approved upstream must be a literal RFC1918 IPv4 address (VM or Private Endpoint).");
  }
  if (typeof tls !== "string" || tls.length > 253 || isIP(tls) ||
      !tls.includes(".") || !tls.split(".").every((label) =>
        /^(?=.{1,63}$)[a-z0-9](?:[a-z0-9-]*[a-z0-9])?$/i.test(label))) {
    throw new Error("TLS server name must be a DNS hostname from the node certificate, not an IP, URL or wildcard.");
  }
  const port = (value) => {
    if (!/^[1-9][0-9]{0,4}$/.test(String(value)) || Number(value) > 65535) {
      throw new Error("Ports must be integers between 1 and 65535.");
    }
    return Number(value);
  };
  for (const value of [name ?? nodeId, region]) {
    if (typeof value !== "string" || !value.trim() || value.length > 80 || /[\u0000-\u001f\u007f]/.test(value)) {
      throw new Error("Name and region must be nonempty text of at most 80 characters without control characters.");
    }
  }
  return {
    "node-data.aca.json": { id: nodeId, upstream: `https://${ip}:${port(dataPort)}`, tlsServerName: tls },
    "cloudcli-nodes.aca.json": {
      id: nodeId, name: (name ?? nodeId).trim(), region: region.trim(),
      upstream: `https://${ip}:${port(workspacePort)}`, tlsServerName: tls,
    },
  };
}

function main() {
  const { values, tokens } = parseArgs({
    options: Object.fromEntries([
      "node-id", "ip", "tls", "name", "region", "data-port", "workspace-port",
    ].map((name) => [name, { type: "string" }]).concat([["help", { type: "boolean" }]])),
    tokens: true, strict: true, allowPositionals: false,
  });
  if (values.help) {
    console.log("node gateway-entry.mjs --node-id <enrolled-id> --ip <approved-private-ip> --tls <certificate-dns> [--name <name>] [--region <region>] [--data-port 8443] [--workspace-port 3001]");
    console.log("Offline JSON entries only. Merge into existing nodes arrays after operator review; no network, secrets or config writes.");
    return;
  }
  const seen = new Set();
  for (const token of tokens) {
    if (token.kind !== "option") continue;
    if (seen.has(token.name)) throw new Error(`Duplicate option: --${token.name}`);
    seen.add(token.name);
  }
  const entries = gatewayEntries({
    nodeId: values["node-id"], ip: values.ip, tls: values.tls,
    name: values.name, region: values.region,
    dataPort: values["data-port"], workspacePort: values["workspace-port"],
  });
  console.log(JSON.stringify(entries, null, 2));
}

if (process.argv[1] && import.meta.url === pathToFileURL(path.resolve(process.argv[1])).href) {
  try { main(); }
  catch (error) { console.error(error.message); process.exitCode = 1; }
}
